### ISSUE TITLE
QUERY_ALL_PACKAGES policy changed

### ISSUE THREAD

**Issue by shinewanna** [g123k/flutter_plugin_device_apps#70] opened 2021-04-01 03:33 UTC
![Screenshot_2021-04-01-09-57-37-787_com google android gm](https://user-images.githubusercontent.com/39454969/113239447-c1f76180-92d0-11eb-9aea-3af53a92eee2.jpg)

Google Play Policy is changed for query install package.So I just want to know is, now, is your package cover for this policy?
Or I've to changed something in my code.

**Comment by g123k** [comment] 2021-04-12 13:16
Duplicate of #53

**Closed by g123k** 2021-04-12 13:16 UTC
