### ISSUE TITLE
FATAL EXCEPTION: pool-2-thread-1 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference

### ISSUE THREAD

**Issue by Pr0t0b0t** [g123k/flutter_plugin_device_apps#39] opened 2020-06-30 19:02 UTC
I'm trying to get the list off my apps for now precisely the length;
When compile this code..!!
I notice that it happens only with **isolates**

     `void isolateApps(int n) {
         DeviceApps.getInstalledApplications(
               onlyAppsWithLaunchIntent: true,
               includeSystemApps: true,
               includeAppIcons: true).then(
      (value) {
          print("Apps isolate value is ${value.length}");
        },
      );
    }`

    `void main() async {
      WidgetsFlutterBinding.ensureInitialized();
       FlutterIsolate.spawn(isolateApps, 0);
       .........}`

I got this error 

> E/AndroidRuntime(16973): FATAL EXCEPTION: pool-2-thread-1
E/AndroidRuntime(16973): Process: com.example.explorer, PID: 16973
E/AndroidRuntime(16973): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
E/AndroidRuntime(16973): 	at fr.g123k.deviceapps.DeviceAppsPlugin.getInstalledApps(DeviceAppsPlugin.java:121)
E/AndroidRuntime(16973): 	at fr.g123k.deviceapps.DeviceAppsPlugin.access$100(DeviceAppsPlugin.java:32)
E/AndroidRuntime(16973): 	at fr.g123k.deviceapps.DeviceAppsPlugin$2.run(DeviceAppsPlugin.java:110)
E/AndroidRuntime(16973): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime(16973): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime(16973): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(16973): 	at java.lang.Thread.run(Thread.java:784)
I/Process (16973): Sending signal. PID: 16973 SIG: 9
Lost connection to device.
Exited (sigterm)

Thanks for your help

**Comment by g123k** [comment] 2020-07-18 07:10
Duplicate of https://github.com/g123k/flutter_plugin_device_apps/issues/31

**Closed by g123k** 2020-07-18 07:10 UTC
