### ISSUE TITLE
DeviceAppsPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Kalyanb447-github** [g123k/flutter_plugin_device_apps#33] opened 2020-04-30 04:14 UTC
Note: C:\Users\kalya\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\device_apps-1.0.9\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java uses or overrides a deprecated API.

**Comment by g123k** [comment] 2020-04-30 07:00
Yes this a warning, not an error.

**Comment by Rosco89** [comment] 2020-05-06 12:12
!!!NOW!! it's a warning.

**Comment by g123k** [comment] 2020-05-06 12:25
Not a bug, closing this

**Closed by g123k** 2020-05-06 12:25 UTC
