### ISSUE TITLE
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread.

### ISSUE THREAD

**Issue by bardram** [g123k/flutter_plugin_device_apps#12] opened 2019-05-28 21:39 UTC
I'm getting this error when running the example app:

```
/AndroidRuntime(25538): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime(25538): Process: fr.g123k.deviceappsexample, PID: 25538
E/AndroidRuntime(25538): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-1-thread-1
E/AndroidRuntime(25538): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(25538): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/AndroidRuntime(25538): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
E/AndroidRuntime(25538): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(25538): 	at fr.g123k.deviceapps.DeviceAppsPlugin$1.run(DeviceAppsPlugin.java:96)
E/AndroidRuntime(25538): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime(25538): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime(25538): 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by g123k** [comment] 2019-05-29 12:29
This is because you are on the dev channel of Flutter.
However I will fix this.

**Comment by g123k** [comment] 2019-05-29 12:30
Duplicate of #11

**Closed by g123k** 2019-05-29 12:30 UTC
